
USE [master]
GO

ALTER DATABASE [nom] SET COMPATIBILITY_LEVEL = 150
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nom] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [nom] SET ANSI_NULLS OFF
GO

ALTER DATABASE [nom] SET ANSI_PADDING OFF
GO

ALTER DATABASE [nom] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [nom] SET ARITHABORT OFF
GO

ALTER DATABASE [nom] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [nom] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [nom] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [nom] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [nom] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [nom] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [nom] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [nom] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [nom] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [nom] SET  ENABLE_BROKER
GO

ALTER DATABASE [nom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [nom] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [nom] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [nom] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [nom] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [nom] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [nom] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [nom] SET RECOVERY FULL
GO

ALTER DATABASE [nom] SET  MULTI_USER
GO

ALTER DATABASE [nom] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [nom] SET DB_CHAINING OFF
GO

ALTER DATABASE [nom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [nom] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [nom] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'nom', N'ON'
GO

ALTER DATABASE [nom] SET QUERY_STORE = OFF
GO

USE [nom]
GO

/****** Object:  Table [dbo].[Table_1]    Script Date: 3/30/2022 11:15:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [nom] SET  READ_WRITE
GO

/****** Object:  Database [nom]    Script Date: 3/30/2022 11:15:38 AM ******/
CREATE DATABASE [nom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nom', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\nom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'nom_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\nom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO

--Syntax Error: Expected DEFAULT_FULLTEXT_LANGUAGE but encountered CATALOG_COLLATION instead.
--/****** Object:  Database [nom]    Script Date: 3/30/2022 11:15:38 AM ******/
--CREATE DATABASE [nom]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'nom', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\nom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'nom_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\nom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
-- WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO

ALTER DATABASE [nom] SET ACCELERATED_DATABASE_RECOVERY = OFF  

GO

--Syntax Error: Incorrect syntax near ACCELERATED_DATABASE_RECOVERY.
--ALTER DATABASE [nom] SET ACCELERATED_DATABASE_RECOVERY = OFF  

GO

CREATE TABLE [dbo].[Table_1](
	[id] [int] NOT NULL,
	[name] [nchar](10) NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

--Syntax Error: Incorrect syntax near OPTIMIZE_FOR_SEQUENTIAL_KEY.
--CREATE TABLE [dbo].[Table_1](
--	[id] [int] NOT NULL,
--	[name] [nchar](10) NULL,
-- CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
--(
--	[id] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
--) ON [PRIMARY]



GO
